#!/bin/bash
  
EXPECTED_ARGS=1
E_BADARGS=65
MYSQL=`which mysql`
  
Q1="CREATE DATABASE IF NOT EXISTS $1;"
Q2="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}"
  
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbname"
  exit $E_BADARGS
fi
  
$MYSQL -uroot -p -e "$SQL"

cat create_tables.sql populate_tables.sql > create_sql
$MYSQL -u root -p $1 < create_sql
rm create_sql